language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tallescs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tallescs/docker-react npm run test -- --coverage