language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tallescs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tallescs/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-203146284689"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
