FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN mkdir -p /app/node_modules && chown -R node:node /app/node_modules
RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

RUN npm install

COPY . .

CMD ["npm", "run", "start"]